
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const inter = Poppins({ weight:["400"] , subsets : ["latin"]});

export const metadata:Metadata = {
  title: 'Healthcare',
  description: 'Generated by Next.js',
}
export default function Layout({children,}: Readonly<{children: React.ReactNode;}>){
  
  return (
    {children}
  );
}